# Generated by Django 5.1.3 on 2024-11-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmap',
            name='edges',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='nodes',
            field=models.TextField(default=''),
        ),
    ]
