# Generated by Django 5.1.3 on 2024-11-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mindmap_edges_mindmap_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmap',
            name='price_gbp',
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=5),
        ),
    ]
